export const projects = [
  {
    bgImage: "/projects/paulaPage.png",
    name: "PaulaTrenuje.pl",
    isPublished: true,
    address: "https://paulatrenuje.pl",
    github: "https://github.com/Adam15-byte/paulatrenuje",
    stack: [
      "typescript",
      "nextjs",
      "tailwind",
      "hook-form",
      "prisma",
      "framer-motion",
      "query",
    ],
  },
  {
    bgImage: "/projects/portfolioPage.png",
    name: "AdamJankowski.dev",
    isPublished: true,
    address: "https://adamjankowski.dev",
    github: "https://github.com/Adam15-byte/my-portfolio",
    stack: ["typescript", "nextjs", "tailwind", "framer-motion", "dayjs"],
  },
  {
    bgImage: "/projects/watches.png",
    name: "Watches App Store",
    isPublished: false,
    github: "https://github.com/Adam15-byte/jaquet-droz-watches",
    stack: ["javascript", "redux", "expo", "react-native", "reanimated"],
  },
  {
    bgImage: "/projects/solanaWallet.png",
    name: "Solana Crypto Wallet",
    isPublished: false,
    github: "https://github.com/Adam15-byte/solana-wallet",
    stack: ["typescript", "react-native"],
  },
  {
    bgImage: "/projects/nike.png",
    name: "Nike Store App",
    isPublished: false,
    github: "https://github.com/Adam15-byte/nike-store-app",
    stack: ["javascript", "expo", "react-native", "reanimated"],
  },
  {
    bgImage: "/projects/pokemon.png",
    name: "Pokemon App",
    isPublished: false,
    github: "https://github.com/Adam15-byte/pokemon---gotta-catch-them-all",
    stack: ["typescript", "expo", "react-native", "redux", "reanimated"],
  },
  {
    bgImage: "/projects/crypto.png",
    name: "Crypto Wallet App",
    isPublished: false,
    github: "https://github.com/Adam15-byte/crypto-app",
    stack: ["javascript", "react-native"],
  },
  {
    bgImage: "/projects/rockpaperscissors.png",
    name: "Rock Paper Scissors Game",
    isPublished: false,
    github: "https://github.com/Adam15-byte/web-rock-paper-scissors",
    stack: ["typescript", "react"],
  },
  {
    bgImage: "/projects/calculator.png",
    name: "iOS Calculator App",
    isPublished: false,
    github: "https://github.com/Adam15-byte/iOS-calculator-app",
    stack: ["javascript", "react-native"],
  },
  {
    bgImage: "/projects/appWelcome.png",
    name: "App Launch Screen",
    isPublished: false,
    github: "https://github.com/Adam15-byte/reanimated-launch-screen",
    stack: ["javascript", "expo", "react-native", "reanimated"],
  },
];
