export const SkillsConfig = {
  HTML: "/tech/html.png",
  javascript: "/tech/javascript.png",
  typescript: "/tech/typescript.png",
  "react native": "/tech/react-native.png",
  react: "/tech/react.png",
  nextjs: "/tech/nextjs.png",
  prisma: "/tech/prisma.png",
  expo: "/tech/expo.png",
  redux: "/tech/redux.svg",
  zustand: "/tech/zustand.png",
  "react query": "/tech/query.png",
  CSS: "/tech/css.png",
  tailwindcss: "/tech/tailwind.png",
  materialui: "/tech/materialui.png",
  "ant design": "/tech/ant-design.png",
  "framer motion": "/tech/framer-motion.png",
  "RN reanimated": "/tech/reanimated.png",
  "hook form": "/tech/hook-form.png",
  dayjs: "/tech/dayjs.png",
  git: "/tech/git.png",
  "Azure DevOps": "/tech/azure-devops.png",
  "github copilot": "/tech/copilot.png",
  "chat gpt": "/tech/chat-gpt.png",
};
